updated lambda invoke to accept config payload

diff --git a/.github/workflows/levr-v1.yml b/.github/workflows/levr-v1.yml
--- a/.github/workflows/levr-v1.yml
+++ b/.github/workflows/levr-v1.yml
@@ -40,26 +40,28 @@ jobs:
                   ls -al ${APP_DIR}/config
                   sed -i "s|MONAD_TESTNET_RPC_URL_1|${{ secrets.MONAD_TESTNET_RPC_URL_1 }}|g" ${APP_DIR}/config/config.json
                   cat ${APP_DIR}/config/config.json
+                  echo "::set-output name=PAYLOAD::$(cat ${APP_DIR}/config/config.json)"
 
-            # - name: Upload to EFS via Lambda
-            #   run: | 
-            #     aws lambda invoke \
-            #       --function-name upload_to_efs \
-            #       --cli-binary-format raw-in-base64-out \
-            #       --payload '{"bucket":"levr-v1-openzeppelin-relayers-config","key":"config.json"}' \
-            #       response.json
+
+            - name: Upload to EFS via Lambda
+              run: | 
+                aws lambda invoke \
+                  --function-name upload_to_efs \
+                  --cli-binary-format raw-in-base64-out \
+                  --payload '${{ steps.generate-config.outputs.PAYLOAD }}' \
+                  response.json
                   
-            #     echo "Response:"
-            #     cat response.json
+                echo "Response:"
+                cat response.json
                 
-            #     # Check response
-            #     if grep -q '"statusCode": 200' response.json; then
-            #       echo "✅ Config uploaded successfully to EFS"
-            #     else
-            #       echo "❌ Upload failed"
-            #       cat response.json
-            #       exit 1
-            #     fi
+                # Check response
+                if grep -q '"statusCode": 200' response.json; then
+                  echo "✅ Config uploaded successfully to EFS"
+                else
+                  echo "❌ Upload failed"
+                  cat response.json
+                  exit 1
+                fi
 
             # - name: Build and Push Docker Image to ECR (main)
             #   uses: docker/build-push-action@v2
